# Generated by Django 4.2.7 on 2023-11-27 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(choices=[('Credit card', 'credit card'), ('Bank transfer', 'bank transfer')], max_length=15)),
                ('payment_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('bill_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.bill')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
